import {Viewer} from './viewer.js?v=00b11dd41a266023';import {ReviewEditor} from './editor.js?v=2dbe9e8dbb4d542e';import {Layout} from './layout.js?v=d77b6865ba378b77';import {formatValue,structured,fieldNames,clinicalSections,sectionFor,localTime,actionNames,displayText} from './format.js?v=f9fa1b201b969df0';
const $=s=>document.querySelector(s),base=new URL('./',import.meta.url),viewer=new Viewer();let info,current,recordId,tab='all',section='',recordToken=0,anchorToken=0,selectedObject=null,draft=null,lastObject=null,pilot=null,pending=false,evidenceContext=null,anchorAbort=null,pilotPromise=null,actionToken=0;
const names={UNREVIEWED:'尚未确认',CONFIRMED:'已确认',NEEDS_REVIEW:'待复核'},key='srs53:'+location.origin+base.pathname;
function el(tag,text='',className=''){const x=document.createElement(tag);x.textContent=text??'';if(className)x.className=className;return x;}function button(text,fn,className=''){const x=el('button',text,className);x.type='button';x.onclick=()=>Promise.resolve(fn()).catch(error=>{$('#modal-status').textContent=error.message;saved(error.message,true);});return x;}
function saved(text,error=false){$('#save-status').textContent=text;$('#save-status').className=error?'error':'success';}
async function request(route,body,options={}){const response=await fetch(new URL(route.replace(/^\//,''),base),{method:body===undefined?'GET':'POST',...options,headers:{...(body!==undefined?{'Content-Type':'application/json','X-CSRF-Token':info?.csrf||''}:{}),...options.headers},body:body===undefined?options.body:JSON.stringify(body)});if(!response.ok){let e;try{e=await response.json();}catch{e={message:'服务器响应无效'};}if(response.status===401)showEntry(e.message);throw Object.assign(Error(e.message),e);}return response;}
async function api(route,body,options){const r=await request(route,body,options);if(!r.headers.get('content-type')?.includes('application/json'))throw Error('服务器响应类型错误，请核对应用路径与后台配置');return r.json();}
function showEntry(message=''){$('#entry').hidden=false;$('#application').hidden=true;$('#entry-status').textContent=message;$('#review-code').value='';}
async function refreshInfo(){info=await api('api/info');$('#entry').hidden=true;$('#application').hidden=false;$('#identity').textContent=info.code+(info.test_only?' · TEST_ONLY':'');saved(info.review_updated_at?'最近审核 '+localTime(info.review_updated_at):'当前审核已就绪');renderNav();}
$('#entry-form').onsubmit=async e=>{e.preventDefault();try{const r=await api('api/login',{code:$('#review-code').value});await refreshInfo();await loadRecord(recordId||info.records[0].id);}catch(e){$('#entry-status').textContent=e.message;}};
function renderNav(){const q=$('#search').value.toLowerCase(),rows=info.records.filter(r=>[r.id,r.study,r.title,r.therapy].join(' ').toLowerCase().includes(q));$('#nav-count').textContent=`${rows.length} / ${info.records.length} 篇`;$('#records').replaceChildren(...rows.map(r=>{const b=button('',()=>loadRecord(r.id),r.id===recordId?'selected':'');b.dataset.record=r.id;b.append(el('strong',r.study),el('small',r.id.replace('rayyan-','')+` · ${r.confirmed}/${r.object_count}`),el('small',r.title));b.title=r.title;return b;}));}
async function loadRecord(id){return transition(()=>loadRecordNow(id));}
async function loadRecordNow(id){const token=++recordToken;invalidateEvidence();viewer.groups=[];viewer.onRegion=null;viewer.clear();layout.set('closed');selectedObject=null;current=null;recordId=id;tab='all';section='';renderNav();$('#results').replaceChildren(el('p','读取当前审核…','empty'));const data=await api('api/record?id='+encodeURIComponent(id));if(token!==recordToken)return;current=data;const title=el('details');title.append(el('summary',data.record.title),el('p',data.record.title));$('#article-head').replaceChildren(el('h2',data.record.study+' · '+id.replace('rayyan-','')),title);if(id.endsWith('2851'))$('#article-head').append(el('p','材料不足：Table S2、S3及Figure S3未取得。','limit'));if(id.endsWith('2705'))$('#article-head').append(el('p','705为共同主记录；430为同发表的支持来源，不增加目标记录。','scope'));$('#result-search').value='';$('#state-filter').value='';renderSources();renderSections();renderResults();await loadPilot(token);}
function renderSections(){if(!current)return;$('#sections').replaceChildren(...clinicalSections.map(s=>{const all=current.objects.filter(o=>sectionFor(o)===s),matches=all.filter(o=>matched(o,false));const b=button(`${s} ${matches.length===all.length?all.length:matches.length+'/'+all.length}`,()=>transition(()=>{section=section===s?'':s;tab='all';renderSections();renderResults();$('#review').scrollTop=0;}),section===s?'selected':'');b.dataset.section=s;b.dataset.total=all.length;b.dataset.matched=matches.length;return b;}));}
function renderSources(){const sel=el('select');sel.setAttribute('aria-label','来源文件');sel.append(new Option('主文 / 支持来源',''));for(const s of current.sources)sel.append(new Option(`${s.record.replace('rayyan-','')} · ${s.roles.includes('primary')?'主文':'支持'} · ${s.page_count}页`,s.source_id));sel.onchange=()=>{const s=current?.sources.find(s=>s.source_id===sel.value);if(s)browseSource(s);};$('#source-select').replaceChildren(sel);}
function matched(o,category=true){const q=$('#result-search').value.toLowerCase(),filter=$('#state-filter').value;return (!category||!section||sectionFor(o)===section)&&(!q||[o.title,o.population,...o.facts.map(f=>f.label+' '+formatValue(f.value))].join(' ').toLowerCase().includes(q))&&(!filter||(filter==='question'?o.has_question:filter==='modified'?o.facts.some(f=>f.modified):o.status===filter));}
function renderResults(){const container=$('#results');container.replaceChildren();if(!current)return;reconcileSelection();$('#back-content').hidden=tab==='all';if(tab==='history'){for(const e of current.events){const card=el('article','','card');card.append(el('h3',(actionNames[e.action]||e.action)+' · '+e.author),el('p',localTime(e.at),'mini'),el('p',e.object_ids.map(id=>current.objects.find(o=>o.id===id)?.title||'本篇信息').join('；')),el('p',e.reason));for(const c of e.changes||[])card.append(el('p',`${c.field}：${formatValue(c.old)} → ${formatValue(c.new)}`));if(e.evidence)card.append(el('p',e.evidence));if(['edit','question','omission','support'].includes(e.action)){const active=current.active_event_ids.includes(e.event_id);card.append(button(active?'撤回记录':'恢复记录',()=>eventControl(e,active?'withdraw':'restore')));}container.append(card);}if(!container.childElementCount)container.append(el('p','本篇暂无审核记录','empty'));return;}
 for(const o of current.objects.filter(o=>matched(o))){const card=el('article','','card'+(selectedObject===o.id?' active':''));card.id=o.id;card.dataset.object=o.id;card.dataset.status=o.status;const head=el('div','','card-title'),heading=el('div');const title=el('h3'),choose=button(o.title==='key'?'文献归属':o.title,()=>selectObject(o),'card-select');choose.setAttribute('aria-pressed',String(selectedObject===o.id));title.append(choose);heading.append(title,el('span',names[o.status],'status'+(o.status==='CONFIRMED'?' confirmed':'')));const actions=el('div','','card-actions');const sourceButton=button(evidenceShown(o.id)?'关闭原文':'查看原文',()=>toggleEvidence(o),'primary');sourceButton.dataset.evidenceObject=o.id;actions.append(sourceButton,button(o.status==='CONFIRMED'?'取消确认':'确认信息',()=>confirmObject(o)),button('修改信息',()=>reviewDialog('edit',o)));head.append(heading,actions);card.append(head,el('p',o.population,'mini'));bindCard(card,o);if(o.facts.some(f=>f.shared))card.append(el('p','含全队列共享背景，不增加组特异样本。','mini'));const fields=el('dl');for(const f of o.facts){const row=el('div','','field'),dd=el('dd',displayText(formatValue(f.value)),f.modified?'modified':'');if(f.modified)dd.append(el('small','原值：'+formatValue(f.baseline_value),'mini'));row.append(el('dt',f.label==='key'?'文献归属':f.label),dd);fields.append(row);}card.append(fields);for(const d of o.derived)card.append(el('p',d.status==='STALE'?'依据已变，派生值待重算':d.known_formula?`既有派生：${d.value}%（n ÷ N × 100）；作者报告值保留。`:d.baseline_description,'scope'));const limits=[...new Set(o.evidence_summary.map(e=>e.restriction).filter(Boolean))],coverage=current.coverage.filter(c=>c.object_ids?.includes(o.id));if(limits.length||coverage.length){const details=el('details');details.append(el('summary','来源限制与未报告说明'));for(const n of limits)details.append(el('p',n,'limit'));for(const c of coverage)details.append(el('p',`${c.item} · ${c.status}：${c.note||''}`,'mini'));card.append(details);}for(const q of current.questions.filter(q=>q.object_ids.includes(o.id)))card.append(el('p',`${q.author} 的问题：${q.reason}`,'limit'));container.append(card);}
 const extra=[...current.coverage.filter(c=>!c.object_ids?.length).map(c=>({title:c.item,population:c.population,text:c.status+'：'+(c.note||'')})),...current.issues.map(i=>({title:i.item,text:i.description+'；'+i.disposition})),...current.questions.filter(q=>!q.object_ids.length).map(q=>({title:'人工补充 · '+q.author,text:q.reason}))].filter(x=>(!section||sectionFor(x)===section)&&(!$('#result-search').value||[x.title,x.text].join(' ').toLowerCase().includes($('#result-search').value.toLowerCase())));if(extra.length){const details=el('details','','supplement');details.append(el('summary','相关限制、未报告与补充说明（'+extra.length+'）'));for(const x of extra)details.append(el('h3',x.title),el('p',x.text,'limit'));container.append(details);}if(!container.childElementCount)container.append(el('p','没有匹配内容，可调整搜索或筛选。','empty'));
}
// Selection, pane layout and rendered evidence have separate lifetimes.
async function transition(action){const token=++actionToken;if(editor.active&&!await editor.requestClose())return false;if(token!==actionToken)return false;await action();return true;}
function evidenceShown(id){const c=evidenceContext;return layout.mode!=='closed'&&c?.status==='ready'&&c.objectId===id&&c.record===recordId&&c.token===anchorToken&&viewer.source?.source_id===c.sourceId&&viewer.page===c.page&&!viewer.failed&&!viewer.stage.hidden&&viewer.stage.dataset.source===c.sourceId&&Number(viewer.stage.dataset.page)===c.page;}
function paintSelection(){document.querySelectorAll('.card[data-object]').forEach(card=>{const active=card.dataset.object===selectedObject;card.classList.toggle('active',active);card.querySelector('.card-select')?.setAttribute('aria-pressed',String(active));const b=card.querySelector('[data-evidence-object]');if(b)b.textContent=evidenceShown(card.dataset.object)?'关闭原文':'查看原文';});$('#pdf-pane').dataset.context=evidenceContext?.status||'none';$('#pdf-pane').dataset.object=evidenceContext?.objectId||'';}
function invalidateEvidence(message='请选择信息查看依据'){anchorToken++;anchorAbort?.abort();anchorAbort=null;evidenceContext=null;viewer.suspend();$('#evidence-select').replaceChildren();$('#page-links').replaceChildren();$('#region-choices').replaceChildren();const sel=$('#source-select select');if(sel)sel.value='';$('#anchor-status').textContent=message;paintSelection();}
function reconcileSelection(){if(selectedObject&&(tab!=='all'||!current.objects.some(o=>o.id===selectedObject&&matched(o)))){selectedObject=null;invalidateEvidence();}}
function bindCard(card,o){let start=null,moved=false;card.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY};moved=false;});card.addEventListener('pointermove',e=>{if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>5)moved=true;});card.addEventListener('pointercancel',()=>{start=null;moved=true;});card.addEventListener('click',e=>{if(e.target.closest('button,a,input,textarea,select,option,details,summary,label,dialog,[role="separator"],[contenteditable]'))return;const dragged=moved;start=null;moved=false;const selection=window.getSelection();if(dragged||(selection&&!selection.isCollapsed&&(card.contains(selection.anchorNode)||card.contains(selection.focusNode))))return;selectObject(o).catch(e=>saved(e.message,true));});}
async function selectObject(o,{open=false,reveal=false,reverse=null}={}){if(!o)return;const record=recordId;return transition(async()=>{if(record!==recordId||!current.objects.some(x=>x.id===o.id))return;o=current.objects.find(x=>x.id===o.id);if(!reveal&&!matched(o))return;if(reveal){tab='all';section='';$('#result-search').value='';$('#state-filter').value='';}const same=selectedObject===o.id;selectedObject=o.id;lastObject=o.id;if(reveal){renderSections();renderResults();document.getElementById(o.id)?.scrollIntoView({block:'start'});}paintSelection();if(reverse){await showRegion(o,reverse);return;}if(layout.mode==='closed'&&!open){if(!same||evidenceContext)invalidateEvidence();return;}if(evidenceShown(o.id))return;if(evidenceContext?.status==='loading'&&evidenceContext.objectId===o.id&&evidenceContext.token===anchorToken)return;await navigate(o);});}
function showObject(id,go=true){const o=current?.objects.find(o=>o.id===id);if(!o)return;if(go)return selectObject(o,{reveal:true});return transition(()=>{tab='all';section='';$('#result-search').value='';$('#state-filter').value='';selectedObject=id;renderSections();renderResults();document.getElementById(id)?.scrollIntoView({block:'start'});if(innerWidth<=820)layout.set('closed');else if(layout.mode==='expanded')layout.set('side');});}
function toggleEvidence(o){if(evidenceShown(o.id)){layout.set('closed');return;}return selectObject(o,{open:true});}
function validEvidence(token,record){return token===anchorToken&&record===recordId&&layout.mode!=='closed';}
async function navigate(o){invalidateEvidence('读取原文位置…');const token=anchorToken,record=recordId;anchorAbort=new AbortController();evidenceContext={status:'loading',objectId:o.id,record,token};if(layout.mode==='closed')layout.set('side');paintSelection();try{await loadPilot(recordToken);if(!validEvidence(token,record))return;const r=await api('api/anchors?object='+encodeURIComponent(o.id),undefined,{signal:anchorAbort.signal});if(!validEvidence(token,record))return;const groups=viewer.groups.filter(g=>g.object_ids.includes(o.id)),source=current.sources.find(s=>s.sha256===pilot?.source_sha256),entries=[...groups.map(g=>({...g,group_ids:[g.id],anchor_id:g.id,source_id:source?.source_id,source_record:source?.record,default_page:g.physical_pages[0]})),...r.entries.filter(a=>!groups.some(g=>g.evidence_keys.includes(a.key)))];const select=el('select');select.setAttribute('aria-label','证据入口');entries.forEach((a,i)=>select.append(new Option(a.label?`${a.label} · 第${a.physical_pages.join('/')}页`:`${a.source_record?.replace('rayyan-','')||''} · ${a.physical_pages.length?'第'+a.physical_pages.join('/')+'页':a.status==='SOURCE_UNAVAILABLE'?'缺材料':'页码待确认'}`,i)));select.onchange=()=>{if(validEvidence(token,record))activate(entries[Number(select.value)],token,record,o.id);};$('#evidence-select').replaceChildren(select);const available=entries.findIndex(a=>a.default_page&&a.status!=='SOURCE_UNAVAILABLE'&&current.sources.some(s=>s.source_id===a.source_id));if(entries.length){select.value=String(available<0?0:available);await activate(entries[Number(select.value)],token,record,o.id);}else{evidenceContext.status='unavailable';$('#anchor-status').textContent='尚无可用原文位置';paintSelection();}}catch(e){if(!validEvidence(token,record)||e.name==='AbortError')return;viewer.suspend();evidenceContext={status:'failed',objectId:o.id,record,token};$('#anchor-status').textContent='原文位置读取失败，请再次选择信息重试';paintSelection();}}
async function activate(a,token,record,objectId,page=a.default_page){if(!validEvidence(token,record))return;const source=current.sources.find(s=>s.source_id===a.source_id);const c=evidenceContext={status:'loading',objectId,record,token,sourceId:source?.source_id,page,anchor:a};viewer.suspend();$('#region-choices').replaceChildren();$('#anchor-status').textContent='读取原文页面…';const sel=$('#source-select select');if(sel)sel.value='';$('#page-links').replaceChildren(...a.physical_pages.map(p=>button('第'+p+'页',()=>{if(validEvidence(token,record))return activate(a,token,record,objectId,p);})));paintSelection();if(!source||!page||a.status==='SOURCE_UNAVAILABLE'){c.status='unavailable';$('#anchor-status').textContent=a.status==='SOURCE_UNAVAILABLE'?'对应材料未取得':a.status==='NOT_APPLICABLE'?'未报告 / 不适用：无精确证据框':'页码待确认';paintSelection();return;}c.message=a.status==='NOT_APPLICABLE'?'未报告 / 不适用：无精确证据框；当前为既有覆盖页，可逐页核对':a.segments?.length?(current.objects.find(o=>o.id===objectId)?.facts.some(f=>f.modified)?'当前值已修改；原标记仅属于原提取依据，不证明新值。':'已定位原提取依据；表头仅为上下文，标记不表示确认。'):'已到相关物理页，请核对原文';await viewer.open(source,page,a,()=>validEvidence(token,record)&&evidenceContext===c);}
async function browseSource(source){actionToken++;invalidateEvidence('读取独立浏览来源…');const token=anchorToken,record=recordId,c=evidenceContext={status:'loading',objectId:null,record,token,sourceId:source.source_id,page:1,message:'独立浏览来源；选择信息可返回对应依据'};if(layout.mode==='closed')layout.set('side');paintSelection();await viewer.open(source,1,null,()=>validEvidence(token,record)&&evidenceContext===c);}
function renderedEvidence(){const c=evidenceContext;if(!c||!validEvidence(c.token,c.record)||viewer.stage.dataset.source!==c.sourceId||Number(viewer.stage.dataset.page)!==c.page)return;c.status='ready';const sel=$('#source-select select');if(sel)sel.value=c.sourceId;$('#anchor-status').textContent=c.message;paintSelection();}
document.addEventListener('pdf-rendered',renderedEvidence);
document.addEventListener('pdf-failed',()=>{const c=evidenceContext;if(c&&validEvidence(c.token,c.record)){c.status='failed';$('#anchor-status').textContent='原文暂时无法打开，可重试或重新选择信息';paintSelection();}});
function movePage(delta){if(!viewer.source)return;actionToken++;const page=viewer.page+delta;if(page<1||page>viewer.source.page_count)return;const c=evidenceContext;if(c?.anchor?.physical_pages?.includes(page)&&c.objectId)return activate(c.anchor,c.token,c.record,c.objectId,page);const source=viewer.source;invalidateEvidence('读取独立浏览页面…');const token=anchorToken,record=recordId;const next=evidenceContext={status:'loading',objectId:null,sourceId:source.source_id,page,record,token,message:'独立浏览页面；选择信息可返回对应依据'};viewer.open(source,page,null,()=>validEvidence(token,record)&&evidenceContext===next);}
async function showRegion(o,{groups,source,page}){if(viewer.source?.source_id!==source.source_id||viewer.page!==page)return;invalidateEvidence();const token=anchorToken,record=recordId,a={group_ids:groups.map(g=>g.id),anchor_id:groups.map(g=>g.id).join(','),segments:groups.flatMap(g=>g.segments),physical_pages:[...new Set(groups.flatMap(g=>g.physical_pages))],default_page:page,source_id:source.source_id};const c=evidenceContext={status:'loading',objectId:o.id,record,token,sourceId:source.source_id,page,anchor:a,message:o.facts.some(f=>f.modified)?'关联原提取依据；当前值已修改，标记不证明新值。':'已返回关联信息；标记不表示人工确认。'};$('#evidence-select').replaceChildren(el('span',groups.map(g=>g.label).join('；')+' · 第'+page+'页'));$('#page-links').replaceChildren(...a.physical_pages.map(p=>button('第'+p+'页',()=>{if(validEvidence(token,record))return activate(a,token,record,o.id,p);})));await viewer.open(source,page,a,()=>validEvidence(token,record)&&evidenceContext===c,false);}
function modal(title){$('#modal').classList.remove('editor');$('#modal-title').textContent=title;$('#modal-body').replaceChildren();$('#modal-actions').replaceChildren();$('#modal-status').textContent='';$('#modal-form').onsubmit=e=>e.preventDefault();if(!$('#modal').open)$('#modal').showModal();}
function labelled(text,input){const label=el('label',text);label.append(input);$('#modal-body').append(label);return input;}function textInput(value='',multiline=false){const x=el(multiline?'textarea':'input');x.value=value??'';return x;}
function reviewDialog(action,o){if(action==='confirm')return confirmObject(o);return transition(()=>editor.open(action,o));}
function eventControl(event,action){editor.open(action,null,{target:event});}
function download(blob,name){const a=el('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),60000);}
async function exportReview(){saved('生成全部累计审核结果…');const r=await request('api/export-review',{parent_revision:info.revision}),name=decodeURIComponent(r.headers.get('content-disposition').split("UTF-8''")[1]);download(await r.blob(),name);saved('审核结果已生成');}
function importDialog(){if(editor.active){editor.requestClose();if(editor.active)return;}modal('载入审核结果');const file=labelled('选择审核结果 XLSX',Object.assign(el('input'),{type:'file',accept:'.xlsx'}));$('#modal-body').append(el('p','先验证和预览；确认后自动备份当前，再整体替换。文件名可以修改。','mini'));$('#modal-actions').append(button('验证并预览',async()=>{if(!file.files[0])throw Error('请选择文件');if(file.files[0].size>8*1024*1024)throw Error('审核文件超过8 MiB输入保护限额，当前审核未改变');const f=file.files[0],bytes=await f.arrayBuffer(),headers={'Content-Type':'application/octet-stream','X-CSRF-Token':info.csrf};const p=await api('api/import-preview',undefined,{method:'POST',headers,body:bytes});$('#modal-status').textContent=`原代号：${p.summary.original_code}\n原审核更新时间：${localTime(p.summary.review_updated_at)}\n文件导出时间：${localTime(p.exported_at)}\n确认 ${p.summary.confirm}；修改 ${p.summary.edit}；问题 ${p.summary.questions}\n当前审核 ${p.current_summary.events} 条事件${p.duplicate?'；内容已一致':''}\n不按文件时间判断哪份更完整。`;$('#modal-actions').replaceChildren(button('载入并继续审核',async()=>{await api('api/import-confirm',undefined,{method:'POST',headers:{...headers,'X-Parent-Revision':p.current_revision,'X-Preview-Token':p.preview_token,'X-Import-Name':encodeURIComponent(f.name)},body:bytes});$('#modal').close();await refreshInfo();await loadRecord(recordId);saved(p.duplicate?'内容已一致':'已载入，原当前审核已自动备份');},'primary'));}));}
async function backupsDialog(){modal('恢复之前的审核');const result=await api('api/backups');if(!result.backups.length)$('#modal-body').append(el('p','暂无自动恢复点'));for(const b of result.backups){const row=el('div','','backup-row');row.append(el('p',`${localTime(b.at)} · ${b.reason} · ${b.summary.events}条事件`),button('预览',async()=>{const p=await api('api/backup-preview?id='+b.id);$('#modal-status').textContent=`原审核更新时间：${localTime(p.summary.review_updated_at)}\n确认 ${p.summary.confirm}；修改 ${p.summary.edit}；问题 ${p.summary.questions}`;$('#modal-actions').replaceChildren(button('恢复此审核（先备份当前）',async()=>{await api('api/restore',{id:b.id,parent_revision:info.revision});$('#modal').close();await refreshInfo();await loadRecord(recordId);},'primary'));}));$('#modal-body').append(row);}}
async function exportReading(){saved('正在生成完整阅读版…');const snap=await api('api/snapshot?revision='+encodeURIComponent(info.revision)),worker=new Worker(new URL('./export-worker.js?v=f9fa1b201b969df0',import.meta.url),{type:'module'});worker.onmessage=e=>{if(e.data.error)saved(e.data.error,true);else{download(new Blob([e.data.buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'SRS53_审核阅读版_v0.3.xlsx');saved('完整阅读版已生成');}worker.terminate();};worker.onerror=e=>{saved('导出失败：'+e.message,true);worker.terminate();};worker.postMessage({snapshot:snap,base:base.href});}
function more(){if(editor.active){editor.requestClose();if(editor.active)return;}modal('更多');$('#modal-body').append(button('下载提取表（紧凑阅读版 Excel）',()=>{$('#modal').close();return exportReading();}),button('审核记录',()=>{$('#modal').close();tab='history';$('#result-search').value='';renderResults();}),button('恢复之前的审核',backupsDialog),button('切换审核代号',async()=>{await api('api/logout',{});$('#modal').close();showEntry();}));if(localStorage.getItem(key+':draft:'+info.code))$('#modal-body').append(button('继续上次未保存草稿',()=>{$('#modal').close();editor.restore();}));}
const editor=new ReviewEditor({context:()=>({code:info?.code,revision:current?.revision,record:recordId,objects:current?.objects||[]}),save:e=>api('api/events',e),done:()=>refreshCurrent(),report:saved,key});const layout=new Layout(viewer,()=>editor.position(),(mode,previous)=>{if(mode==='closed'){actionToken++;invalidateEvidence();}else if(previous==='closed'&&selectedObject&&!viewer.source&&!evidenceContext){const o=current?.objects.find(o=>o.id===selectedObject);if(o)navigate(o);}paintSelection();});
async function refreshCurrent(){const id=recordId,scroll=$('#review').scrollTop;await refreshInfo();const data=await api('api/record?id='+encodeURIComponent(id));if(recordId!==id)return;current=data;renderSections();renderResults();$('#review').scrollTop=scroll;}
async function confirmObject(o){if(pending)return;const record=recordId,objectId=o.id,action=o.status==='CONFIRMED'?'unconfirm':'confirm';pending=true;try{await transition(async()=>{if(record!==recordId)return;await api('api/events',{event_id:crypto.randomUUID(),parent_revision:current.revision,action,object_ids:[objectId],record,reason:'',evidence:''});await refreshCurrent();saved(action==='unconfirm'?'已取消本块确认':'已确认本块信息');});}finally{pending=false;}}
async function loadPilot(record=recordToken){if(!pilot){pilotPromise??=api('./pilot-924.json?v=f9fa1b201b969df0').catch(()=>({groups:[],error:'924索引不可用，保留原页码导航。'}));const loaded=await pilotPromise;if(record!==recordToken)return;pilot=loaded;}if(record!==recordToken||!current)return;const valid=current.record.id===pilot.record&&info.project.baseline_sha256===pilot.baseline_sha256&&current.sources.some(s=>s.sha256===pilot.source_sha256&&s.page_count===pilot.source_pages);viewer.groups=valid?pilot.groups.filter(g=>{const source=current.sources.find(s=>s.sha256===pilot.source_sha256);return g.source_sha256===source.sha256&&g.coordinate_version==='PDF_USER_SPACE_QUADS_V1'&&g.object_ids.every(id=>current.objects.some(o=>o.id===id))&&g.evidence_keys.every(k=>current.objects.some(o=>o.evidence_keys.includes(k)))&&g.segments.every(s=>{const b=source.pages[s.page-1]?.crop_box;return b&&s.source_sha256===source.sha256&&s.quad?.length===8&&s.quad.every((v,i)=>Number.isFinite(v)&&v>=b[i%2]-1&&v<=b[i%2+2]+1);});}):[];$('#show-extracted-label').hidden=!valid;viewer.onRegion=groups=>{const token=anchorToken,record=recordId,source=viewer.source,page=viewer.page;if(!source||layout.mode==='closed')return;const box=$('#region-choices'),ids=[...new Set(groups.flatMap(g=>g.object_ids))];box.replaceChildren(el('p','选择原区域关联的信息；表头仅为上下文'));for(const id of ids){const o=current.objects.find(o=>o.id===id);if(o)box.append(button(o.title,()=>{if(validEvidence(token,record))return selectObject(o,{reveal:true,reverse:{groups,source,page}});}));}};}
$('#search').oninput=renderNav;$('#result-search').oninput=()=>{actionToken++;renderSections();renderResults();};$('#state-filter').onchange=()=>{actionToken++;renderSections();renderResults();};$('#export-review').onclick=()=>exportReview().catch(e=>saved(e.message,true));$('#import-review').onclick=importDialog;$('#more').onclick=more;$('#omission').onclick=()=>reviewDialog('omission');$('#toggle-nav').onclick=()=>document.body.classList.toggle('nav-hidden');$('#back-result').onclick=()=>showObject(selectedObject,false);$('#back-content').onclick=()=>{tab='all';renderResults();};$('#zoom').onchange=e=>{viewer.zoom=e.target.value;viewer.render(false);};$('#rotate').onclick=()=>{viewer.rotation=(viewer.rotation+90)%360;viewer.render(false);};$('#prev-page').onclick=()=>movePage(-1);$('#next-page').onclick=()=>movePage(1);$('#show-extracted').onchange=e=>{viewer.showAll=e.target.checked;viewer.render(false);};$('#next-unreviewed').onclick=()=>{if(!current)return;const list=current.objects.filter(o=>o.status!=='CONFIRMED'&&matched(o));if(!list.length){saved('当前筛选下没有未审核信息');return;}showObject(list[(list.findIndex(o=>o.id===lastObject)+1)%list.length].id);};try{await refreshInfo();await loadRecord(info.records[0].id);layout.apply();}catch(e){showEntry(e.code==='UNAUTHORIZED'?'':e.message);}
