import {formatValue,structured,fieldNames} from './format.js?v=f9fa1b201b969df0';
const $=s=>document.querySelector(s),el=(tag,text='')=>{const x=document.createElement(tag);x.textContent=text;return x;};
const equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
export class ReviewEditor{
 constructor({context,save,done,report,key}){Object.assign(this,{context,save,done,report,key});this.active=false;document.addEventListener('keydown',e=>{if(this.active&&e.key==='Escape'){e.preventDefault();e.stopPropagation();this.requestClose();}});$('#close-modal').onclick=()=>this.requestClose();$('#modal').addEventListener('cancel',e=>{e.preventDefault();this.requestClose();});window.addEventListener('beforeunload',e=>{if(this.dirty){this.persist();e.preventDefault();e.returnValue='';}});}
 get dirty(){return this.active&&!equal({...this.data,mode:''},{...this.initial,mode:''});}
 storageKey(){return this.key+':draft:'+this.context().code;}
 persist(){if(this.dirty)localStorage.setItem(this.storageKey(),JSON.stringify({meta:this.meta,data:this.data,initial:this.initial}));else if(this.active){try{if(JSON.parse(localStorage.getItem(this.storageKey())||'null')?.meta.event_id===this.meta.event_id)localStorage.removeItem(this.storageKey());}catch{}}$('#modal').dataset.dirty=String(this.dirty);}
 button(text,fn){const b=el('button',text);b.type='button';b.onclick=()=>Promise.resolve(fn()).catch(e=>this.error(e));return b;}
 error(e){$('#modal-status').textContent=e.message+'；输入仍保留。';this.report(e.message,true);}
 close(){if(this.busy)return;const origin=this.origin,scroll=this.originScroll;this.active=false;this.data=null;this.meta=null;$('#modal').classList.remove('editor');$('#modal').close();$('#close-choice')?.remove();this.saveAction=null;requestAnimationFrame(()=>{const target=origin?.isConnected?origin:document.querySelector(`[data-object="${this.objectId}"] button`);target?.focus({preventScroll:true});$('#review').scrollTop=scroll;});}
 requestClose(){if(this.busy)return;if(!this.dirty){this.close();return;}if($('#close-choice'))return;const choice=el('div');choice.id='close-choice';choice.setAttribute('role','group');choice.setAttribute('aria-label','未保存修改');choice.append(el('p','有未保存的修改'),this.button('保存并关闭',()=>this.submit()),this.button('不保存并关闭',()=>{localStorage.removeItem(this.storageKey());this.close();}),this.button('继续编辑',()=>choice.remove()));$('#modal-actions').append(choice);}
 open(action,o,{target=null,restore=null}={}){if(this.active)return;const c=this.context();if(!restore){let previous;try{previous=JSON.parse(localStorage.getItem(this.storageKey())||'null');}catch{}if(previous){if(previous.meta.record===c.record&&previous.meta.action===action&&previous.meta.target_event===target?.event_id&&JSON.stringify(previous.meta.object_ids)===JSON.stringify(o?[o.id]:[]))restore=previous;else{this.report('另有未保存草稿，请从“更多”恢复并保存或放弃后，再修改其他信息。草稿文献：'+previous.meta.record.replace('rayyan-',''),true);return;}}}this.origin=document.activeElement;this.originScroll=$('#review').scrollTop;this.objectId=o?.id;this.object=o;this.active=true;this.busy=false;this.meta={event_id:crypto.randomUUID(),parent_revision:c.revision,action,object_ids:o?[o.id]:[],record:c.record,...(target?{target_event:target.event_id}:{})};this.data={mode:action,values:Object.fromEntries((o?.facts||[]).filter(f=>f.editable).map(f=>[f.id,f.value])),reason:'',evidence:''};this.initial=structuredClone(this.data);if(restore){this.meta=restore.meta;this.data=restore.data;this.initial=restore.initial;}$('#modal').classList.add('editor');$('#modal-title').textContent=o?'修改信息 · '+o.title:action==='omission'?'补充信息':action==='withdraw'?'撤回记录':'恢复记录';$('#modal-body').replaceChildren();$('#modal-actions').replaceChildren();$('#modal-status').textContent='';$('#modal-form').onsubmit=e=>{e.preventDefault();this.submit();};
 const scope=el('p',o?`本块 ${o.fact_ids.length} 个字段；原证据仍作为历史背景。`:'补充内容不会自动改写已提取事实。');scope.className='scope';$('#modal-body').append(scope);
 if(o&&['edit','question'].includes(action)){const modes=el('div');modes.className='editor-modes';const edit=this.button('修改信息',()=>{this.data.mode='edit';this.renderBody();this.persist();}),question=this.button('仅提问题',()=>{this.data.mode='question';this.renderBody();this.persist();});modes.append(edit,question);$('#modal-body').append(modes);}
 this.body=el('div');$('#modal-body').append(this.body);this.renderBody();this.saveAction=this.button('保存',()=>this.submit());this.saveAction.className='primary';$('#modal-actions').append(this.saveAction);if(!$('#modal').open)$('#modal').show();this.position();this.persist();}
 position(){const d=$('#modal');if(!this.active)return;const r=$('#review').getBoundingClientRect();if(r.width<20)return;d.style.setProperty('--editor-left',Math.max(8,r.left+8)+'px');d.style.setProperty('--editor-width',Math.max(280,r.width-16)+'px');d.style.setProperty('--editor-top',Math.max(8,r.top+8)+'px');d.style.setProperty('--editor-height',Math.max(250,r.height-16)+'px');}
 label(text,input,host=this.body){const label=el('label',text);label.append(input);host.append(label);return input;}
 text(value='',multiline=false){const x=el(multiline?'textarea':'input');x.value=value??'';return x;}
 renderBody(){this.body.replaceChildren();if(this.data.mode==='edit'){const fields=this.object.facts.filter(f=>f.editable);if(fields.length){const select=el('select');select.id='field-select';fields.forEach(f=>select.append(new Option(f.label,f.id)));select.value=this.selectedField&&fields.some(f=>f.id===this.selectedField)?this.selectedField:fields[0].id;this.label('修改字段',select);const holder=el('div');this.body.append(holder);const render=()=>{this.selectedField=select.value;const f=fields.find(x=>x.id===select.value);holder.replaceChildren(el('p','已保存值：'+formatValue(f.value)));const value=this.data.values[f.id],obj=structured(value);if(obj){const walk=(v,parts=[])=>{if(v!==null&&typeof v==='object'){Object.entries(v).forEach(([k,x])=>walk(x,[...parts,k]));}else{const input=this.text(v);this.label(parts.map(k=>fieldNames[k]||k).join(' / '),input,holder);input.oninput=()=>{const changed=structured(this.data.values[f.id]);let dest=changed;parts.slice(0,-1).forEach(k=>dest=dest[k]);dest[parts.at(-1)]=typeof v==='number'?(input.value.trim()&&Number.isFinite(Number(input.value))?Number(input.value):input.value):typeof v==='boolean'?(input.value==='true'?true:input.value==='false'?false:input.value):v===null&&!input.value?null:input.value;const original=structured(f.value);this.data.values[f.id]=equal(changed,original)?f.value:JSON.stringify(changed);this.persist();};}};walk(obj);}else{const input=this.text(value,true);input.id='edit-value';this.label('新值',input,holder);input.oninput=()=>{this.data.values[f.id]=input.value===String(f.value??'')?f.value:typeof f.value==='number'?(input.value.trim()&&Number.isFinite(Number(input.value))?Number(input.value):input.value):input.value;this.persist();};const empty=this.button('设为空值',()=>{this.data.values[f.id]=null;render();this.persist();});holder.append(empty);}};select.onchange=render;render();}}
 const reason=this.text(this.data.reason,true);reason.id='edit-reason';this.label(this.data.mode==='edit'?'修改说明（选填）':['question','omission'].includes(this.data.mode)?(this.data.mode==='question'?'问题正文（必填）':'补充内容（必填）'):'说明（选填）',reason);reason.oninput=()=>{this.data.reason=reason.value;this.persist();};const evidence=this.text(this.data.evidence,true);evidence.id='edit-evidence';this.label('补充原文依据或页码（选填）',evidence);evidence.oninput=()=>{this.data.evidence=evidence.value;this.persist();};}
 async submit(){if(this.busy||!this.active)return;try{const event={...this.meta,action:this.data.mode,reason:this.data.reason,evidence:this.data.evidence};if(event.action==='edit'){event.changes=Object.entries(this.data.values).filter(([id,v])=>!equal(v,this.initial.values[id])).map(([fact_id,value])=>({fact_id,old:this.initial.values[fact_id],new:value}));if(!event.changes.length)throw Error('没有需要保存的字段修改');}if(['question','omission'].includes(event.action)&&!event.reason.trim())throw Error('请填写内容');this.busy=true;this.saveAction.disabled=true;$('#close-modal').disabled=true;await this.save(event);localStorage.removeItem(this.storageKey());this.busy=false;const objectId=this.objectId,scroll=this.originScroll;this.close();try{await this.done(event);requestAnimationFrame(()=>{document.querySelector(`[data-object="${objectId}"] .card-actions button:last-child`)?.focus({preventScroll:true});$('#review').scrollTop=scroll;});this.report('已保存');}catch(refreshError){this.report('已保存；页面刷新失败，请刷新页面查看最新审核：'+refreshError.message,true);}}catch(e){this.persist();this.error(e);}finally{this.busy=false;if(this.saveAction)this.saveAction.disabled=false;$('#close-modal').disabled=false;}}
 restore(){const text=localStorage.getItem(this.storageKey());if(!text)return false;const saved=JSON.parse(text),c=this.context();if(saved.meta.record!==c.record)throw Error('草稿属于另一篇文献，请先打开 '+saved.meta.record.replace('rayyan-',''));const o=c.objects.find(o=>o.id===saved.meta.object_ids[0]);this.open(saved.meta.action,o,{restore:saved});return true;}
}
